import { Component } from '@angular/core';

@Component({
  selector: 'albums',
  templateUrl: './albums.component.html',
  styleUrls: ['./albums.component.css']
})
export class AlbumsComponent {
  album = [
    {"img": "../../assets/images/something-wild.png", "albumName": "Something Wild", "albumInfo": "Something Wild , Finlandiyalı melodik death metal grubu Children of Bodom'un 1997'de Finlandiya'da ve 1998'de dünya çapında piyasaya sürülenilk uzun metrajlı albümüdür. Albüm yayınlandıktan sonra müzik eleştirmenleri tarafından evrensel beğeni topladı. 2020 yılında Metal Hammer dergisitarafından 1997'nin en iyi 20 metal albümünden biri seçildi."},
    {"img": "../../assets/images/hatebreeder.jpeg", "albumName": "Hatebreeder", "albumInfo": "Hatebreeder, Finlandiyalı heavy metal grubu Children of Bodom`un ikinci stüdyo albümü. 'Deluxe Edition', 2005 yılında bonus materyalle piyasaya sürüldü. Ayrıca 2008'de yeniden yayınlandı.2005 yılında Hatebreeder , Rock Hard dergisinin Tüm Zamanların En İyi 500 Rock ve Metal Albümü kitabında 492. sırada yer aldı ."},
    {"img": "../../assets/images/follow-the-reaper.jpg", "albumName": "Follow The Reaper", "albumInfo": "Follow the Reaper, Fin melodik death metal grubu Children of Bodom'un üçüncü stüdyo albümü."},
    {"img": "../../assets/images/hate-crew-deathroll.jpeg", "albumName": "Hate Crew Deathroll", "albumInfo": "Hate Crew Deathroll , Finlandiyalı melodik death metal grubu Children of Bodom'un 2003 yılında Century Media etiketiyledördüncü stüdyo albümüdürVe bu aynı zamanda, orijinal ritim gitaristleri Alexander Kuoppala'nın 2003 yılında gruptan ayrılacağı için beş orijinal üyenin tümü ile kaydedilecek son Children of Bodom albümü. MTV2 Headbangers Ball'daki 'Needled 24/7' müzik videosu. 'Needled 24/7' aynı zamanda heavy metal belgeseli Metal: A Headbanger's Journey ve 2012 korku komedi video oyunu Lollipop Chainsaw'da da yer aldı."},
    {"img": "../../assets/images/are-you-dead-yet.jpg", "albumName": "Are You Dead Yet?", "albumInfo": "Are You Dead Yet? Fin melodik death metal grubu Children of Bodom'un beşinci stüdyo albümü. 14 Eylül 2005'te Finlandiya'da ve uluslararası olarak 25 Ekim 2005'te Century Media etiketi altında yayınlandı. Orijinal ritim gitaristleri Alexander Kuoppala'nın ayrılması nedeniyle gitarist Roope Latvala'nın ( Stone , Sinergy , eski Waltari ) yer aldığı ilk Children of Bodom albümüdür. Bu albümde grup drop C akortunu kullanırken, genellikle D standardını kullandılar. Güç metaliDaha önce öne çıkan etkiler de bu albümde büyük ölçüde azaltılarak daha basit bir performans ve daha yavaş tempolar elde ediliyor. Gitarlar müzikal hakimiyeti korurken, klavyeler de miksajda daha aşağıya düşürüldü."},
    {"img": "../../assets/images/Blooddrunk.jpg", "albumName": "Blooddrunk", "albumInfo": "<b>Blooddrunk</b>, Fin melodik death metal grubu Children of Bodom'un altıncı stüdyo albümüdür, 9 Nisan 2008 tarihinde piyasaya sürülmüştür.Blooddrunk, Children of Bodom'un bir önceki 'Are You Dead Yet?' isimli albümüne oranla daha melodik olmakla birlikte daha hızlı tempolu şarkılar da barındıran ve thrash metal etkenlerinin arttığı bir yapıya sahiptir."},
    {"img": "../../assets/images/skeletonsalbum.jpg", "albumName": "Skeletons In The Closet", "albumInfo": "<b>Skeletons in the Closet</b> , Finlandiyalı melodik death metal grubu Children of Bodom'un 22 Eylül 2009'da Spinefarm Records aracılığıyla çıkardığı bir derleme albümüdür. Albümde 'Hell Is for Children', 'Antisocial', 'War Inside My Head' ve 'Waiting' şarkıları için henüz yayınlanmamış dört cover bulunuyor ancak daha önce çıkan şarkılara remiks yapılıyor ve yeni detaylar duyulabiliyor. Japonca baskı SHM-CD formatında basılmıştır."},
    {"img": "../../assets/images/relentless-reckless-forever.jpg", "albumName": "Relentless Reckless Forever", "albumInfo": "Relentless Reckless Forever, Finlandiyalı melodik death metal grubu Children of Bodom'un 8 Mart 2011'de Spinefarm Records, Fearless Records ve Nuclear Blast aracılığıyla çıkardığı yedinci albümü. Adında 'Bodom' geçen bir şarkısı olmayan ilk Children of Bodom albümüdür."},
    {"img": "../../assets/images/halo-of-blood.jpg", "albumName": "Halo Of Blood", "albumInfo": "Halo of Blood , Finlandiyalı melodik death metal grubu Children of Bodom'un sekizinci stüdyo albümü. 7 Haziran 2013'te Avrupa'da ve 11 Haziran'da Kuzey Amerika'da Nuclear Blast Records tarafından yayınlandı. Japonya'da albüm, 29 Mayıs 2013'te Marquee Inc. tarafından yayınlandı. Bu, gitarist Roope Latvala'nın Mayıs 2015'te gruptan atılmadan önceki son albümü olacaktı."},
    {"img": "../../assets/images/i-worship-chaos.jpeg", "albumName": "I Worship Chaos", "albumInfo": "I Worship Chaos , Finlandiyalı melodik death metal grubu Children of Bodom'un dokuzuncu stüdyo albümü. 2 Ekim 2015'te yayınlandı. 2005'teki Are You Dead'den bu yana Mayıs 2015'te gruptan kovulması nedeniyle gitarist Roope Latvala'nın yer almadığı ilk albüm ve bu, grubun dört parçalı ilk albümü oldu. Alexi Laiho'nun tüm gitar görevlerini üstlendiği grup. Grup ilk kez ticari bir kayıt stüdyosu kullanmadı. Bunun yerine, sesin ambiyansını geliştirmek için dönüştürülmüş bir depo kullanmayı tercih ettiler. Bu albümde grup, albümün çoğunda drop B akortunu ve önceki albümlerde kullanılan drop C akort ve D standardı yerine 'Morrigan', 'Hold Your Tongue' ve 'Suicide Bomber' şarkılarında D-flat akort kullandı. Bu aynı zamanda bunu, Something Wild'dan bu yana D-flat akort kullanan ilk albüm yapıyor."},
    {"img": "../../assets/images/hexed.jpeg", "albumName": "Hexed", "albumInfo": "Hexed , Fin melodik death metal grubu Children of Bodom'un onuncu ve son stüdyo albümü. 8 Mart 2019'da yayınlandı. 2016 yılında gruba üye olan gitarist Daniel Freyberg'in yer aldığı tek albüm , Kasım 2019'da gruptan ayrılan uzun süredir üyeler olan Jaska Raatikainen , Henkka Seppälä ve Janne Wirman'ın yer aldığı son albüm ve sonuncusu. Children of Bodom albümü, Alexi Laiho tarafından 2020'nin sonlarında ölümünden önce kaydedilecek ve piyasaya sürülecek . Ayrıca, ayrılan üyeler (Raatikainen, Seppälä ve Wirman) hakları için başvurdukları için Children of Bodom adının kullanıldığı son kayıttır. adı, bu nedenle Laiho'ya adı kullanmaya devam etmesi için üçünden de izin verilmesi gerekir. Laiho ve Freyberg, Laiho'nun ölümüne kadar Bodom After Midnight adıyla farklı bir kadroyla devam edeceklerdi."},
]
}
